Flowpack:
  JsonApi:
    pagination:
      defaultPageSize: 25
      maximumPageSize: 100
    response:
      headers:
        'Access-Control-Allow-Origin': '*'
    endpoints:
      'api':
        baseUrl: 'api'
        version: 'v1'
        resources: []
Neos:
  Flow:
    mvc:
      routes:
        'Flowpack.JsonApi': true
